# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Rego TreeSitter parser CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn
    - run: yarn test
    - run: |
        npx tree-sitter build-wasm\
        && (npx tree-sitter playground --quiet &)\
        && sleep 5 \
        && wget -p -k localhost:8000 \
        && mv localhost:8000 static_playground \
        && wget localhost:8000/tree-sitter.wasm -O static_playground/tree-sitter.wasm \
        && wget localhost:8000/tree-sitter-parser.wasm -O static_playground/tree-sitter-parser.wasm \
        && sed -i'' -e 's/LANGUAGE_BASE_URL = ""/LANGUAGE_BASE_URL = "tree-sitter-rego"/' static_playground/index.html
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        folder: static_playground
